version: "3"
services:
  flask:
    container_name: main
    image: ${dockerImageMaster}
    restart: always
    ports:
     - "5000:5000"
    volumes: 
      - DataVolume:/mydata
    logging: 
      driver: awslogs
      options:
        awslogs-group: flask-up
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web

  flask-slave:
    container_name: slave
    image: ${dockerImageSlave}
    ports:
     - "5001:5001"
    volumes:
      - DataVolume:/mydata
    logging: 
      driver: awslogs
      options:
        awslogs-group: flask-up
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web

volumes:
  DataVolume:
