version: "3"
services:
  flask:
    container_name: main
    image: "${dockerImageMaster}"
    restart: always
    ports:
     - "5000:5000"
    volumes: 
      - DataVolume:/mydata

  flask-slave:
    container_name: slave
    image: "${dockerImageSlave}"
    ports:
     - "5001:5001"
    volumes:
      - DataVolume:/mydata

volumes:
  DataVolume:
